### ISSUE TITLE
GOOD FIRST ISSUE: Solve spelling mistakes in the docs

### ISSUE THREAD

**Issue by maximalmaxx** [maximalmaxx/clipboardy#3]
**Description**
For newcomers to practise the workflow of contributing to projects.

**What to do**
-Solve all spelling mistakes found in the documentation (Normal documentation and DevDocs)

Thanks for your help, and have fun contributing,
maximalmaxx

**Comment by maximalmaxx** [comment]
@jey-exp, sounds great, you are one of the very first people to see my project! I will assign you, have fun working on your first contribution! Good luck, let me know if there are any questions.

**Comment by maximalmaxx** [comment]
@jey-exp, I´ve also uploaded the Developer Documentation today, could you go over it as well?
Thank you,
maximalmaxx

**Comment by jey-exp** [comment]
Thankyou so much! 
Going through docs. Will ask if help is needed

**Comment by maximalmaxx** [comment]
@jey-exp, is everything working so far?

**Comment by jey-exp** [comment]
Are you on discard?
If so, can you share your ID, I need a little confirmation regarding the issue

**Comment by maximalmaxx** [comment]
No, sadly not on Discord. Whats the problem?

**Comment by jey-exp** [comment]
Thanks 
Will message you there

**Comment by maximalmaxx** [comment]
Your name is jey and the hastag is 6690? I can't find -jey6690#0 or jey#6690

**Comment by maximalmaxx** [comment]
Worked now, I send the request

**Comment by jey-exp** [comment]
okay, Accepted :)
